### ISSUE TITLE
is:issue is:open 这个图里结构时先con1x1升维，再dwconv3x3,后面conv1x1降维，但你的代码却是，先dwconv3x3,再con1x1升维，再conv1x1降维？这不一样吧？？？？

### ISSUE THREAD

**Issue by dataconc** [RooKichenn/pytorch-MOAT#1]

**Comment by RooKichenn** [comment]
你可能理解错了，我用的是timm中的dwconv组件，具体实现在这里：[https://github.com/rwightman/pytorch-image-models/blob/main/timm/models/efficientnet_blocks.py](url)，官方只提供了升维的代码，而在moat具体实现时在dwconv外面加了一层conv卷积来降维：[https://github.com/RooKichenn/pytorch-MOAT/blob/main/classification/moat.py#L123](url)，看完这些也许你会有新的理解。

**Comment by dataconc** [comment]
对啊，就是你用的那个timm中的DepthwiseSeparableConv这个类，这个类里面是先执行dwconv3x3的再执行conv1x1升维的

**Comment by dataconc** [comment]
你看里面具体的实现，就是先dwcon3x3,再pwconv(即conv1x1)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RooKichenn/pytorch-MOAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月11日(星期五) 晚上7:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RooKichenn/pytorch-MOAT] is:issue is:open 这个图里结构时先con1x1升维，再dwconv3x3,后面conv1x1降维，但你的代码却是，先dwconv3x3,再con1x1升维，再conv1x1降维？这不一样吧？？？？ (Issue #1)





 
你可能理解错了，我用的是timm中的dwconv组件，具体实现在这里：https://github.com/rwightman/pytorch-image-models/blob/main/timm/models/efficientnet_blocks.py，官方只提供了升维的代码，而在moat具体实现时在dwconv外面加了一层conv卷积来降维：https://github.com/RooKichenn/pytorch-MOAT/blob/main/classification/moat.py#L123，看完这些也许你会有新的理解。

**Comment by RooKichenn** [comment]
请问有什么问题吗？请你去看看mbconv的官方定义，moat画的不一样，但是代码实现就是先分组提取特征，再进行升维，如果你想先升维再提取特征，请考虑你的计算量是否违背了mbconv设计的初衷？

**Comment by dataconc** [comment]
我只是想说，这实现跟图片里的不同而，只是提出一下我个人的疑惑，还有，官方的的或者说一开始的mobilenetv2,v3,都是先conv1x1升维，dwcon,最后conv1x1降维



>
